### ISSUE TITLE
error: ValidationError(CustomResourceDefinition.spec): missing required field "scope"

### ISSUE THREAD

**Issue by banbanandroid** [AliyunContainerService/arena#30]
this is for Closed issues #8 

I think we can add scope filed valued "Namespaced" to CustomResourceDefinition part for TFJOB in the ```tf-operator.yaml``` and I find ksonnet makes it to Namespaced automatically , like below, we just add it [here](https://github.com/AliyunContainerService/arena/blob/master/kubernetes-artifacts/tf-operator/tf-operator.yaml#L208)
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tfjobs.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: TFJob
    plural: tfjobs
    singular: tfjob
  ## add scope filed here
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            tfReplicaSpecs:
              properties:
                Chief:
                  properties:
                    replicas:
                      maximum: 1
                      minimum: 1
                      type: integer
                PS:
                  properties:
                    replicas:
                      minimum: 1
                      type: integer
                Worker:
                  properties:
                    replicas:
                      minimum: 1
                      type: integer
  version: v1alpha2
```
this will solve the problem for arena when it create CRD-TFJOB where k8s version>=1.11.0, of cource if exec command below also can solve this problem
```
kubectl create -f arena/kubernetes-artifacts/tf-operator/tf-operator.yaml --validate=false
```
